# Generated by Django 5.1.1 on 2024-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins_app', '0004_alter_pagebannersmodel_banner_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebannersmodel',
            name='banner_images',
            field=models.ImageField(upload_to='images/page_banners'),
        ),
    ]
