# Generated by Django 5.1.1 on 2024-09-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('cms_plugins_app', '0005_alter_pagebannersmodel_banner_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTechnologyModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('tech_title', models.TextField(default='Technology', max_length=200)),
                ('tech_description', models.TextField(default='Technology Description', max_length=200)),
                ('tech_icon', models.ImageField(upload_to='images/tech_icons')),
                ('associated_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_product', to='cms.page', verbose_name='Associated Page')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
